### ISSUE TITLE
Update Datastore Format

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [mobilecoinofficial/auxin#72]
Currently auxin is having issues due to a change in Signal's datastore. Updates to this should be made when possible.

**Comment by cxloe** [comment]
It doesn't actually seem to be ( much of an ) auxin issue. as per https://github.com/mobilecoinofficial/forest/issues/220

**Comment by iamalwaysuncomfortable** [comment]
Excellent if this is still the case the issue can be closed!
